# Generated by Django 2.1.5 on 2019-02-10 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='AsientoDisponibles',
            field=models.IntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Pasajeros',
            field=models.CharField(default='[]', editable=False, max_length=100000),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Patente',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='Hora_Inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='NumeroAsientoAsginado',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Rut',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
