# Generated by Django 2.1.5 on 2019-02-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaPrincipal', '0002_auto_20190210_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Eliminado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='Eliminado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ApellidoMaterno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ApellidoPaterno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='Eliminado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
