# Generated by Django 2.1.5 on 2019-02-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaPrincipal', '0003_auto_20190213_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trayecto',
            name='Horario',
        ),
        migrations.AddField(
            model_name='trayecto',
            name='FechaCreacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='Hora_Fin',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='Hora_Inicio',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
