# Generated by Django 2.1.5 on 2019-02-13 22:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgenciaPrincipal', '0004_auto_20190213_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='BusAsignado',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='AgenciaPrincipal.Bus'),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='NumeroAsientoAsginado',
            field=models.IntegerField(editable=False, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
